
###
GET http://localhost:8080/v1/firstname/Bart
Accept: application/json

###
GET http://localhost:8080/v1/remote/firstname/Bart
Accept: application/json

###

###
GET http://localhost:8080/v1/lastname/Simpson
Accept: application/json

###
GET http://localhost:8080/v1/remote/lastname/Simpson
Accept: application/json

###
